In [ ]:
import numpy as np

values = np.random.binomial(1, 0.5, 10)
print("Generated Values:", values)
working = np.sum(values)
print("Working Bulbs:", working)


Generated Values: [0 1 0 0 0 1 1 1 0 0]
Working Bulbs: 4


In [ ]:
import numpy as np

heads = np.random.binomial(5, 0.5, 5)
print("Number of heads in each experiment:")
print(heads)


Number of heads in each experiment:
[3 3 3 3 1]


In [ ]:
import numpy as np

arrivals = np.random.poisson(2, 10)
print("Customer Arrivals:", arrivals)
print("Highest Customers in an Hour:", np.max(arrivals))


Customer Arrivals: [1 2 1 0 1 2 1 3 4 2]
Highest Customers in an Hour: 4


In [ ]:
import numpy as np

values = np.random.geometric(0.5, 10)
print("Generated Values:", values)
print("Maximum Attempts:", np.max(values))


Generated Values: [2 3 3 1 1 1 3 1 1 3]
Maximum Attempts: 3


In [ ]:
import numpy as np

print("Bernoulli Distribution:")
print(np.random.binomial(1, 0.5, 5))

print("\nBinomial Distribution:")
print(np.random.binomial(5, 0.5, 5))

print("\nGeometric Distribution:")
print(np.random.geometric(0.5, 5))

print("\nPoisson Distribution:")
print(np.random.poisson(2, 5))


Bernoulli Distribution:
[1 0 1 0 0]

Binomial Distribution:
[4 2 2 4 3]

Geometric Distribution:
[1 2 2 1 1]

Poisson Distribution:
[2 2 0 1 1]
